name = "explain-my-bill"
main = "src/index.js"
compatibility_date = "2025-12-21"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "PAID_SESSIONS"
id = "5c80b0fbb48b4a708d55806ae6788dc5"
